// DRIVER STANDINGS (Top 10)
export const mockDriverStandings = [
    {
        position: 1,
        driverId: "max_verstappen",
        givenName: "Max",
        familyName: "Verstappen",
        code: "VER",
        number: "1",
        team: "Red Bull Racing",
        teamId: "red_bull",
        teamColor: "#1e40af",
        points: 575,
        wins: 19,
        podiums: 21,
        nationality: "Dutch",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/2024-08-25_Motorsport%2C_Formel_1%2C_Gro%C3%9Fer_Preis_der_Niederlande_2024_STP_3973_by_Stepro_%28medium_crop%29.jpg/800px-2024-08-25_Motorsport%2C_Formel_1%2C_Gro%C3%9Fer_Preis_der_Niederlande_2024_STP_3973_by_Stepro_%28medium_crop%29.jpg",
    },
    {
        position: 2,
        driverId: "perez",
        givenName: "Sergio",
        familyName: "Pérez",
        code: "PER",
        number: "11",
        team: "Red Bull Racing",
        teamId: "red_bull",
        teamColor: "#1e40af",
        points: 285,
        wins: 2,
        podiums: 8,
        nationality: "Mexican",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Sergio_P%C3%A9rez_2023.jpg/800px-Sergio_P%C3%A9rez_2023.jpg",
    },
    {
        position: 3,
        driverId: "hamilton",
        givenName: "Lewis",
        familyName: "Hamilton",
        code: "HAM",
        number: "44",
        team: "Mercedes",
        teamId: "mercedes",
        teamColor: "#00d2be",
        points: 234,
        wins: 2,
        podiums: 11,
        nationality: "British",
        image: "https://upload.wikimedia.org/wikipedia/commons/a/ac/Lewis_Hamilton_2022_S%C3%A3o_Paulo_Grand_Prix_%2852498120773%29_%28cropped%29.jpg",
    },
    {
        position: 4,
        driverId: "leclerc",
        givenName: "Charles",
        familyName: "Leclerc",
        code: "LEC",
        number: "16",
        team: "Ferrari",
        teamId: "ferrari",
        teamColor: "#dc0000",
        points: 307,
        wins: 5,
        podiums: 13,
        nationality: "Monegasque",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/2024_Bahrain_GP_-_Charles_Leclerc_%28cropped%29.jpg/800px-2024_Bahrain_GP_-_Charles_Leclerc_%28cropped%29.jpg",
    },
    {
        position: 5,
        driverId: "sainz",
        givenName: "Carlos",
        familyName: "Sainz",
        code: "SAI",
        number: "55",
        team: "Ferrari",
        teamId: "ferrari",
        teamColor: "#dc0000",
        points: 290,
        wins: 3,
        podiums: 12,
        nationality: "Spanish",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Carlos_Sainz_Jr._2023.jpg/800px-Carlos_Sainz_Jr._2023.jpg",
    },
    {
        position: 6,
        driverId: "norris",
        givenName: "Lando",
        familyName: "Norris",
        code: "NOR",
        number: "4",
        team: "McLaren",
        teamId: "mclaren",
        teamColor: "#ff8700",
        points: 349,
        wins: 3,
        podiums: 18,
        nationality: "British",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/2024-08-25_Motorsport%2C_Formel_1%2C_Gro%C3%9Fer_Preis_der_Niederlande_2024_STP_3975_by_Stepro_%28cropped2%29.jpg/800px-2024-08-25_Motorsport%2C_Formel_1%2C_Gro%C3%9Fer_Preis_der_Niederlande_2024_STP_3975_by_Stepro_%28cropped2%29.jpg",
    },
    {
        position: 7,
        driverId: "russell",
        givenName: "George",
        familyName: "Russell",
        code: "RUS",
        number: "63",
        team: "Mercedes",
        teamId: "mercedes",
        teamColor: "#00d2be",
        points: 175,
        wins: 1,
        podiums: 6,
        nationality: "British",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/68/George_Russell_2023.jpg/800px-George_Russell_2023.jpg",
    },
    {
        position: 8,
        driverId: "piastri",
        givenName: "Oscar",
        familyName: "Piastri",
        code: "PIA",
        number: "81",
        team: "McLaren",
        teamId: "mclaren",
        teamColor: "#ff8700",
        points: 291,
        wins: 2,
        podiums: 9,
        nationality: "Australian",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Oscar_Piastri_2023.jpg/800px-Oscar_Piastri_2023.jpg",
    },
    {
        position: 9,
        driverId: "alonso",
        givenName: "Fernando",
        familyName: "Alonso",
        code: "ALO",
        number: "14",
        team: "Aston Martin",
        teamId: "aston_martin",
        teamColor: "#006f62",
        points: 206,
        wins: 0,
        podiums: 8,
        nationality: "Spanish",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Alonso_2016.jpg/800px-Alonso_2016.jpg",
    },
    {
        position: 10,
        driverId: "stroll",
        givenName: "Lance",
        familyName: "Stroll",
        code: "STR",
        number: "18",
        team: "Aston Martin",
        teamId: "aston_martin",
        teamColor: "#006f62",
        points: 74,
        wins: 0,
        podiums: 3,
        nationality: "Canadian",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Lance_Stroll_2023.jpg/800px-Lance_Stroll_2023.jpg",
    },
];

// CONSTRUCTOR STANDINGS (Top 10)
export const mockConstructorStandings = [
    {
        position: 1,
        constructorId: "red_bull",
        name: "Red Bull Racing",
        nationality: "Austrian",
        teamColor: "#1e40af",
        points: 860,
        wins: 21,
        podiums: 29,
        drivers: ["Max Verstappen", "Sergio Pérez"],
        driverIds: ["max_verstappen", "perez"],
        logo: "https://upload.wikimedia.org/wikipedia/en/4/44/Red_bull_racing.png",
    },
    {
        position: 2,
        constructorId: "mercedes",
        name: "Mercedes",
        nationality: "German",
        teamColor: "#00d2be",
        points: 409,
        wins: 3,
        podiums: 17,
        drivers: ["Lewis Hamilton", "George Russell"],
        driverIds: ["hamilton", "russell"],
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Mercedes_AMG_Petronas_F1_Logo.svg/200px-Mercedes_AMG_Petronas_F1_Logo.svg.png",
    },
    {
        position: 3,
        constructorId: "ferrari",
        name: "Ferrari",
        nationality: "Italian",
        teamColor: "#dc0000",
        points: 597,
        wins: 8,
        podiums: 25,
        drivers: ["Charles Leclerc", "Carlos Sainz"],
        driverIds: ["leclerc", "sainz"],
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Scuderia_Ferrari_Logo.svg/200px-Scuderia_Ferrari_Logo.svg.png",
    },
    {
        position: 4,
        constructorId: "mclaren",
        name: "McLaren",
        nationality: "British",
        teamColor: "#ff8700",
        points: 640,
        wins: 5,
        podiums: 27,
        drivers: ["Lando Norris", "Oscar Piastri"],
        driverIds: ["norris", "piastri"],
        logo: "https://upload.wikimedia.org/wikipedia/en/thumb/6/66/McLaren_Racing_logo.svg/200px-McLaren_Racing_logo.svg.png",
    },
    {
        position: 5,
        constructorId: "aston_martin",
        name: "Aston Martin",
        nationality: "British",
        teamColor: "#006f62",
        points: 280,
        wins: 0,
        podiums: 11,
        drivers: ["Fernando Alonso", "Lance Stroll"],
        driverIds: ["alonso", "stroll"],
        logo: "https://upload.wikimedia.org/wikipedia/en/thumb/7/7a/Aston_Martin_Aramco_Cognizant_F1.svg/200px-Aston_Martin_Aramco_Cognizant_F1.svg.png",
    },
    {
        position: 6,
        constructorId: "alpine",
        name: "Alpine",
        nationality: "French",
        teamColor: "#0090ff",
        points: 13,
        wins: 0,
        podiums: 0,
        drivers: ["Pierre Gasly", "Esteban Ocon"],
        driverIds: ["gasly", "ocon"],
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Alpine_F1_Team_Logo.svg/200px-Alpine_F1_Team_Logo.svg.png",
    },
    {
        position: 7,
        constructorId: "williams",
        name: "Williams",
        nationality: "British",
        teamColor: "#005aff",
        points: 13,
        wins: 0,
        podiums: 0,
        drivers: ["Alexander Albon", "Logan Sargeant"],
        driverIds: ["albon", "sargeant"],
        logo: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f9/Williams_Racing_logo.svg/200px-Williams_Racing_logo.svg.png",
    },
    {
        position: 8,
        constructorId: "alphatauri",
        name: "RB (AlphaTauri)",
        nationality: "Italian",
        teamColor: "#2b4562",
        points: 42,
        wins: 0,
        podiums: 0,
        drivers: ["Yuki Tsunoda", "Daniel Ricciardo"],
        driverIds: ["tsunoda", "ricciardo"],
        logo: "https://upload.wikimedia.org/wikipedia/en/thumb/3/3d/Scuderia_AlphaTauri_logo.svg/200px-Scuderia_AlphaTauri_logo.svg.png",
    },
    {
        position: 9,
        constructorId: "haas",
        name: "Haas F1 Team",
        nationality: "American",
        teamColor: "#ffffff",
        points: 47,
        wins: 0,
        podiums: 0,
        drivers: ["Nico Hülkenberg", "Kevin Magnussen"],
        driverIds: ["hulkenberg", "magnussen"],
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Haas_F1_Team_Logo.svg/200px-Haas_F1_Team_Logo.svg.png",
    },
    {
        position: 10,
        constructorId: "alfa",
        name: "Alfa Romeo (Sauber)",
        nationality: "Swiss",
        teamColor: "#900000",
        points: 0,
        wins: 0,
        podiums: 0,
        drivers: ["Valtteri Bottas", "Zhou Guanyu"],
        driverIds: ["bottas", "zhou"],
        logo: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Alfa_Romeo_F1_Team_Orlen_Logo.svg/200px-Alfa_Romeo_F1_Team_Orlen_Logo.svg.png",
    },
];

// Helper: Get position badge color (for top 3)
export const getPositionColor = (position) => {
    if (position === 1)
        return {
            bg: "bg-yellow-500/20",
            text: "text-yellow-500",
            border: "border-yellow-500",
        };
    if (position === 2)
        return {
            bg: "bg-gray-400/20",
            text: "text-gray-400",
            border: "border-gray-400",
        };
    if (position === 3)
        return {
            bg: "bg-orange-500/20",
            text: "text-orange-500",
            border: "border-orange-500",
        };
    return {
        bg: "bg-neutral-800",
        text: "text-gray-400",
        border: "border-neutral-700",
    };
};

export const getPodiumEmoji = (position) => {
    if (position === 1) return "🥇";
    if (position === 2) return "🥈";
    if (position === 3) return "🥉";
    return "";
};
